SELECT COUNT(DISTINCT USER_ID) CNT FROM 
	(SELECT	
		USER_ID,
		CREATED_AT,
		PRODUCT_ID,
		RANK() OVER (PARTITION BY USER_ID ORDER BY CREATED_AT) NR_DA_COMPRA,
		RANK() OVER (PARTITION BY USER_ID, PRODUCT_ID ORDER BY CREATED_AT)
		RANKEAMENTO_PRODUTO
	FROM marketing_campaign) T
WHERE T.RANKEAMENTO_PRODUTO < 2 AND T.NR_DA_COMPRA > 1